### ISSUE TITLE
How to serve with Hypercorn

### ISSUE THREAD

**Issue by shepherd1530** [python-trio/trio-websocket#176]
Hello there,

How can I serve my server implementation with Hypercorn? I am getting an "Address already in use" because Hypercorn is bound to the port.

My main looks like below.

```
async def main(*args, **kwargs):
    async with trio.open_nursery() as nursery:
        nursery.start_soon(listen_redis)

        await serve_websocket(
            echo_server,
            "127.0.0.1",
            5400,
            ssl_context=None,
            handler_nursery=nursery,
        )
```

All help will be appreciated. Thanks!

**Comment by belm0** [comment]
There was an old ticket #1 asking about how to upgrade an HTTP connection to websocket, but I don't know how to do it.

If you only need a websocket server, I suggest looking at quart-trio, which is built on hypercorn.

> If you happen to only need a server, using Quart via the [quart-trio](https://github.com/pgjones/quart-trio)
extension may suffice.  While trio-websocket is more flexible, Quart covers
both HTTP and WebSocket within a single framework, and serving both from the
same port is straightforward.  There has yet to be a performance comparison.

**Comment by shepherd1530** [comment]
> There was an old ticket #1 asking about how to upgrade an HTTP connection to websocket, but I don't know how to do it.
> 
> If you only need a websocket server, I suggest looking at quart-trio, which is built on hypercorn.
> 
> > If you happen to only need a server, using Quart via the [quart-trio](https://github.com/pgjones/quart-trio)
> > extension may suffice.  While trio-websocket is more flexible, Quart covers
> > both HTTP and WebSocket within a single framework, and serving both from the
> > same port is straightforward.  There has yet to be a performance comparison.

I am more interested in a pure websocket only library sadly. Looks like I will just maintain my starlette implementation for now. Thanks.
